plugins:
  - name: solidity
  - name: vyper
  - name: hardhat
  - name: infura
  - name: tokens

# require OpenZeppelin Contracts
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.7.3

solidity:
  import_remapping:
    - "@openzeppelin=openzeppelin/v4.7.3/contracts"

contracts_folder: src

default_ecosystem: ethereum

ethereum:
  default_network: local
  local:
    default_provider: hardhat
