## defaults for all profiles
[profile.default]
src = 'src'                                  # the source directory
test = 'foundry_test'                        # the test directory
out = 'out'                                  # the output directory (for artifacts)
libs = ['lib']                               # a list of library directories
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/contracts'
]                                             # a list of remappings
cache = true                                 # whether to cache builds or not
cache_path = 'cache'                         # where the cache is stored if enabled
force = true                                 # whether to ignore the cache (clean build)
ffi = true                                   # whether to enable foreign function interface (ffi) cheatcodes or not
verbosity = 3                                # the verbosity of tests

